### PR TITLE
Fix compiler warning for AsyncJson’s JSON_MIMETYPE variable type.

### PR DESCRIPTION
**Pull request by buddydvd**
This commit fixes the following compiler warning:

    In file included from src/Program.cpp:21:0:
    lib/ESPAsyncWebServer/src/AsyncJson.h:39:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
    constexpr char* JSON_MIMETYPE = "application/json";

@tfelix had mentioned about this issue an earlier— see: https://github.com/me-no-dev/ESPAsyncWebServer/issues/390#issuecomment-409378991

### CODE REVIEW

**Comment by buddydvd** [comment]
Here's more context:

When `JSON_MIMETYPE` was *first* introduced in https://github.com/me-no-dev/ESPAsyncWebServer/commit/d7399a7664bce76e9939837fd6cf51bd272ef588, it was defined as a _non-const_ global pointer to a `const char`:

    const char* JSON_MIMETYPE = "application/json";

Non-const global variables have external linkage. So, if you include `AsyncJson.h` in two different implementation files, you get the multiple definitions error. This is what #390 was about.

PR #396 (implementing the proposed solution described in #390) defined `JSON_MIMETYPE` as follow:

    constexpr char* JSON_MIMETYPE = "application/json";

This change fixes the redefinition error since `constexpr` specifier turned `JSON_MIMETYPE` a const global variable. _Const global variables in C++ have internal linkage by default_— so no multiple definitions error!

However, it may appear `JSON_MIMETYPE` still defines a pointer that points to a `const char` (when in fact, it doesn't). The change turned `JSON_MIMETYPE` from a _mutable-pointer to-a-const-char_ to a _const-pointer-to-a-mutable-char_. It's like as it were defined as follow:

    char* const JSON_MIMETYPE = "application/json";

Assigning the string literal `application/json` (`const char`) to a pointer that points to a mutable `char` is the reason for the compiler warning.

This PR restores the type that the `JSON_MIMETYPE` pointer points to (i.e., from `char` back to `const char`).
