### ISSUE TITLE
AsyncTCP@1.0.3 doesn't work with Espressif 32@1.5.0

### ISSUE THREAD

**Issue by Tyrrx** [me-no-dev/ESPAsyncWebServer#479]
Processing heltec_wifi_lora_32 (platform: espressif32; board: heltec_wifi_lora_32; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/heltec_wifi_lora_32.html
PLATFORM: Espressif 32 > Heltec WIFI LoRa 32
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 32 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP Async WebServer> 1.2.0
|   |-- <AsyncTCP> 1.0.3
|   |-- <Crypto> 0.2.0
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0

compilation terminated.
*** [.pioenvs\heltec_wifi_lora_32\src\main.cpp.o] Error 1
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:32: error: field 'call' has incomplete type 'tcpip_api_call_data'
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: forward declaration of 'struct tcpip_api_call_data'
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_output(tcp_pcb*)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:295:70: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_output_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:295:70: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_write(tcp_pcb*, const char*, size_t, uint8_t)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:311:69: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_write_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:311:69: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_recved(tcp_pcb*, size_t)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:326:70: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_recved_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:326:70: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_connect(tcp_pcb*, ip_addr_t*, uint16_t, tcp_connected_fn)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:342:71: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_connect_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:342:71: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_close(tcp_pcb*)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:356:69: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_close_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:356:69: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_abort(tcp_pcb*)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:371:69: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_abort_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:371:69: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'esp_err_t _tcp_bind(tcp_pcb*, ip_addr_t*, uint16_t)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:386:68: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_bind_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:386:68: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In function 'tcp_pcb* _tcp_listen_with_backlog(tcp_pcb*, uint8_t)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:401:70: error: invalid conversion from 'err_t (*)(tcpip_api_call_data*) {aka signed char (*)(tcpip_api_call_data*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call*)}' [-fpermissive]
tcpip_api_call(_tcp_listen_api, (struct tcpip_api_call_data*)&msg);
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:401:70: error: cannot convert 'tcpip_api_call_data*' to 'tcpip_api_call*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call*)'
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call_data' is incomplete
struct tcpip_api_call_data call;
^
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp: In member function 'void AsyncClient::_dns_found(ip_addr*)':
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:643:33: error: invalid use of incomplete type 'struct ip_addr'
connect(IPAddress(ipaddr->u_addr.ip4.addr), _connect_port);
^
In file included from .piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.cpp:24:0:
.piolibdeps\AsyncTCP_ID1826\src\AsyncTCP.h:46:8: note: forward declaration of 'struct ip_addr'
struct ip_addr;
^
*** [.pioenvs\heltec_wifi_lora_32\lib528\AsyncTCP_ID1826\AsyncTCP.cpp.o] Error 1

**Comment by atanisoft** [comment]
you need to either downgrade to AsyncTCP 1.0.1 or upgrade to Espressif 32@1.6.0 (arduino-esp32 1.0.1). Upgrading Espressif32 is the route to go as there are a number of fixes included in that over 1.5.0 (which is arduino-esp32 1.0.0).
